apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/operator-type: non-standalone
  name: neutron-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NeutronAPI is the Schema for the neutronapis API
      displayName: Neutron API
      kind: NeutronAPI
      name: neutronapis.neutron.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      - description: API tls type which encapsulates for API services
        displayName: API
        path: tls.api
      - description: Ovn GenericService - holds the secret for the OvnDb client cert
        displayName: Ovn
        path: tls.ovn
      version: v1beta1
  description: Neutron Operator
  displayName: Neutron Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Network
  - Neutron
  links:
  - name: Neutron Operator
    url: https://github.com/openstack-k8s-operators/neutron-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
